### ISSUE TITLE
stats.xml is invalid XML

### ISSUE THREAD

**Issue by reckart** [UniversalDependencies/UD_Russian-GSD#1]
The stats.xml file is not a valid XML file:

```
  <forms unique="29960" /><!-- ,, ., в, и, --, на, ), (, ``, &#39;&#39;, -, с, по, года, году -->
```

A `--` may not appear in an XML comment

Observed in UD Treebank  v 1.3.

**Comment by dan-zeman** [comment]
Thanks for reporting, fixed in dev branch.
